[package]
name = "missingno"
version = "0.0.1"
authors = ["Andrew O'Neil <andy@andyofniall.net>"]
edition = "2024"
license = "MIT"

[[bin]]
name = "missingno"
path = "src/main.rs"

[dependencies]
bitflags = "2.10.0"
clap = { version = "4.5.53", features = ["derive"] }
iced = { version = "0.14.0", features = [
    "canvas",
    "advanced",
    "lazy",
    "smol",
    "svg",
] }
iced_aw = { version = "0.13.0", default-features = false, features = [
    "drop_down",
] }
replace_with = "0.1.8"
rfd = "0.16.0"
rgb = "0.8.52"
